files:
  - source: /gui-orchid/lib/l10n/app_en.arb
    translation: /gui-orchid/lib/l10n/app_%two_letters_code%.arb
  - source: /gui-orchid/assets/docs/help/help_en.html
    translation: /gui-orchid/assets/docs/help/help_%two_letters_code%.html
