[package]
name = "riscy"
edition = "2021"

[dependencies]
bincode = "1.3"
cxx = "1.0"
risc0-zkvm = { path = "../risc0/risc0/zkvm", features = ["prove"] }

[lib]
path = "riscy.rs"
crate-type = ["staticlib"]
