name: CI
on: [push]
jobs:

  build-win-cli:
    runs-on: ubuntu-latest

    steps:
    - name: install mingw-w64
      run: DEBIAN_FRONTEND=noninteractive sudo -EH apt-get -y install mingw-w64

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule status
      id: git-submodule-status
      run: echo "::set-output name=hash::$(git submodule status | sed -e 's/^.\([^ ]*\) \([^ ]*\).*/\2 \1/' | LANG=C sort | openssl sha1 -binary | xxd -p -c20)"
    - uses: actions/cache@v2
      with:
        path: .git/modules
        key: git-modules-${{ steps.git-submodule-status.outputs.hash }}
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Windows client
      run: make -j3 -C cli-shared target=win
    - uses: actions/upload-artifact@v1
      with:
        name: orchidcd-win
        path: cli-shared/out-win/x86_64/orchidcd.exe

